### ISSUE TITLE
xmlrpc bug in python 2.7.1

### ISSUE THREAD

**Issue by janrito** [cakebread/yolk#3]
There is a bug in the with xmlrpclib.py in python 2.7.1:

```
File "/usr/lib/python2.7/site-packages/yolk/pypi.py", line 65, in request
  return(self.parse_response(fhandle)) 
File "/usr/lib64/python2.7/xmlrpclib.py", line 1449, in parse_response 
  if response.getheader("Content-Encoding", "") == "gzip":  
AttributeError: addinfourl instance has no attribute 'getheader' 
```

Here is somebody else's patch:
https://bitbucket.org/dbinit/yolk/src/5f679466e2d0/yolk/pypi.py

**Comment by cakebread** [comment]
Thank you, Alejandro.

Can you tell me how to reproduce this with python 2.7, please? I've tried it on a couple systems and I don't get that traceback when trying to query pypi with -L, -C, -D etc. 

I've created a hotfix branch with this patch (hotfix/issue3).

**Comment by janrito** [comment]
I get the exception when I try to run anything that requires a connection to PyPI, including -L, -C, -D, -U, etc... 

The error seems to affect 2.7.1 only, which is the standard on Fedora 15. I have other installations with the latest 2.7.2 python, which run yolk fine. I don't have a 2.7 install to test with.

**Comment by janrito** [comment]
PyPy 1.7 is compatible with 2.7.1. It suffers from the same bug.

**Comment by cakebread** [comment]
Thank you, I hadn't tested 2.7.1. I'm moving this weekend but may get
a release out.
I'll see if I can test pypy and add the build on http://cakebread.info/jenkins

On Fri, Feb 10, 2012 at 4:45 AM, Alejandro Giacometti
reply@reply.github.com
wrote:

**Comment by bobbyi** [comment]
I just encountered this bug and the patched code linked from janrito's first post worked for me.
